#####################
#  Redirect Rules   #
#####################
[[redirects]]
  from = "/api/*"
  to = "http://homeinventorybackend-env.eba-ncy44xmq.us-east-1.elasticbeanstalk.com"
  status = 302
  force = false
