[[redirects]]
  from = "/api/v1/home-inventory"
  to = "http://homeinventorybackend-env.eba-ncy44xmq.us-east-1.elasticbeanstalk.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"